# Generated by Django 5.2.7 on 2025-10-02 17:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='agentes/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], max_length=20)),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela/Terreno'), ('oficina', 'Oficina'), ('comercial', 'Local/Bodega')], max_length=30)),
                ('region', models.CharField(choices=[('Metropolitana de Santiago', 'Metropolitana de Santiago')], default='Metropolitana de Santiago', max_length=40)),
                ('comuna', models.CharField(choices=[('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Conchalí', 'Conchalí'), ('El Bosque', 'El Bosque'), ('Estación Central', 'Estación Central'), ('Huechuraba', 'Huechuraba'), ('Independencia', 'Independencia'), ('La Cisterna', 'La Cisterna'), ('La Florida', 'La Florida'), ('La Granja', 'La Granja'), ('La Pintana', 'La Pintana'), ('La Reina', 'La Reina'), ('Las Condes', 'Las Condes'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Maipú', 'Maipú'), ('Ñuñoa', 'Ñuñoa'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñalolén', 'Peñalolén'), ('Providencia', 'Providencia'), ('Pudahuel', 'Pudahuel'), ('Puente Alto', 'Puente Alto'), ('Quilicura', 'Quilicura'), ('Quinta Normal', 'Quinta Normal'), ('Recoleta', 'Recoleta'), ('Renca', 'Renca'), ('San Joaquín', 'San Joaquín'), ('San Miguel', 'San Miguel'), ('San Ramón', 'San Ramón'), ('Santiago', 'Santiago'), ('Vitacura', 'Vitacura'), ('San Bernardo', 'San Bernardo'), ('El Monte', 'El Monte'), ('Isla de Maipo', 'Isla de Maipo'), ('Padre Hurtado', 'Padre Hurtado'), ('Peñaflor', 'Peñaflor'), ('Talagante', 'Talagante')], max_length=60)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('precio_clp', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dormitorios', models.PositiveSmallIntegerField(default=0)),
                ('banos', models.PositiveSmallIntegerField(default=0)),
                ('estacionamientos', models.PositiveSmallIntegerField(default=0)),
                ('sup_construida_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sup_terreno_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ano_construccion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('destacada', models.BooleanField(default=False)),
                ('publicada', models.BooleanField(default=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agente')),
            ],
            options={
                'ordering': ['-destacada', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('origen', models.CharField(default='web', max_length=50)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.propiedad')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
