# Generated by Django 5.2.7 on 2025-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('cta_text', models.CharField(blank=True, max_length=40, verbose_name='Texto botón')),
                ('cta_url', models.URLField(blank=True, verbose_name='URL botón')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor número = aparece antes')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide de carrusel',
                'verbose_name_plural': 'Slides de carrusel',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
