# Generated by Django 5.2.7 on 2025-10-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.propiedad'),
        ),
    ]
