# Generated by Django 5.2.7 on 2025-10-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_precio_uf_and_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comuna',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
