# Generated by Django 5.2.7 on 2026-04-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lead_comuna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'verbose_name': 'Agente Inmobiliario', 'verbose_name_plural': 'Equipo de Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='carouselslide',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Banner de Portada', 'verbose_name_plural': 'Fotos de Portada (Banners)'},
        ),
        migrations.AlterModelOptions(
            name='imagenpropiedad',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Foto de Galería', 'verbose_name_plural': 'Galería de fotos'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Mensaje de Cliente', 'verbose_name_plural': 'Mensajes de Clientes (Leads)'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'ordering': ['-destacada', '-creado'], 'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
    ]
